; nhan mot so voi 6
; GIA? SU'? SO^' CA^`N NHA^N D-ANG CHU'A TRONG THANH GHI CO' NHA~N = NUMBER . MEM[NUMBER] = 123

.ORIG	X3000
LD	R1,SIX		; R1 <- 6
LD	R2,NUMBER	; R2 <- 123
AND	R3,R3,#0	; XOA R3 DE LAM LU'U TI'CH QUA VIEC CO^.NG DO^'N

; PHA^`N VO`NG LAP
;

AGIAN	ADD	R3,R3,R2
	ADD	R1,R1,#-1	;THEO DOI SO LAN LAP

BRp	AGIAN 	;LAPLAI
;

HALT

NUMBER	.BLKW	123
SIX	.FILL X0006
;

.END
