.ORIG X3000
LEA R0 , CHAO_MUNG	; YEU CAU NGUOI DUNG NHAP GIA TRI TU 0 -> 9
PUTS			; IN THONG BAO LEN MAN HINH

TRAP X23		; NHAP SO VAO

; check edd or even
AND R1,R1,#1

BRz CHAN
BRp LE

CHAN LEA R0,CHUOI_CHAN
	PUTS
	HALT

LE LEA R0,CHUOI_LE
	PUTS
	HALT

CHAO_MUNG .STRINGZ "HAY NHAP MOT KY TU TU 0 -> 9"
CHUOI_CHAN .STRINGZ "KY SO LA CHAN"
CHUOI_LE .STRINGZ "KY SO LA LE"

.END