; PHEP NHAN HAI SO KHONG DAU DUOC LUU TRONG O NHO CUA MAY TINH
; PHEP NHAN NAY KHONG KIEM TRA DIEU KHIEN NHAN CHO 0
.ORIG	x3000
    LDI R1, FIRST_NUM
    LDI R2, SECOND_NUM
    AND	R3,	R3,	#0
AGAIN   ADD	R3,	R3,	R1
        ADD	R2,	R2,	#-1
BRP AGAIN       

    STI	R3,	RESULT

    HALT
    FIRST_NUM .FILL	    X4000
    SECOND_NUM .FILL	X4001
    RESULT  .FILL	X4002
.END