.ORIG	x3000
    LD R5, ASCII_TONUM
    LEA R0,NHAPSODAU
    PUTS
    IN
    ADD R1,R0,R5
    LEA R0,NHAPSOSAU
    PUTS
    IN
    ADD R2,R0,R5
    AND	R3,	R3,	#0
AGAIN   ADD	R3,	R3,	R1
        ADD	R2,	R2,	#-1
BRP AGAIN       

ADD R1,R3,0 ; CHUYEN KET QUA NHAN VAO R1

;MODULE IN HAI SO KET QUA LEN MAN HINH
; khoi tao o nho ::: R2 hang chuc ::: R3 hang don vi :: RO chuyen ma ASCII
AND R0,R0,#0
AND R2,R2,#0
AND R3,R3,#0
LD R4, ASCII_NUM
; dem hang chuc
CONT_CHUC	ADD R1,R1,#-10

		BRN STOP_CHUC

ADD R2,R2,#1
BR CONT_CHUC

STOP_CHUC	

;nhap hang don vi

ADD R3,R1,#10

; KIEM TRA IN HANG CHUC, HANG DON VI
		ADD R2,R2,#0
		BRZ IN_DONVI 

	ADD R0,R2,R4	;	R2->ASCII
	OUT
IN_DONVI
	AND R0,R0,#0
	ADD R0,R3,R4
	OUT
HALT
NHAPSODAU .STRINGZ "NHAP SO THU NHAT"
NHAPSOSAU .STRINGZ "NHAP SO THU HAI"
ASCII_NUM .FILL X30
ASCII_TONUM .FILL X-30
GTRI .FILL X4000

.END