.ORIG	x3000
    IN
    BRNZP MODULE_CHUYEN_MA

    NHAP_TIEP IN
    BRNZP MODULE_CHUYEN_MA

    MODULE_CHUYEN_MA
    ;CHECK CO PHAI SO NHO HON HOAC BANG 9
    LD	R2,	NUM_9
    ADD	R1 , R0 , R2
    BRP NHAPSAI

    ;CHECK CO PHAI SO LON HON HOAC BANG 0
    LD	R2,	NUM_0
    ADD	R1 , R0 , R2
    BRN NHAPSAI

    ;NEU KHONG LOI ->  CHUYEN MA ASCII SANG SO
    STR	R1,	R0,	#0
    ADD R0,R0,#0

NHAPSAI LEA	R0,	CHUOI_ERROR_O_9
                PUTS
                HALT
    CHUOI_ERROR_O_9 .STRINGZ	"KHONG CHUYEN DUOC,KHONG PHAI KY SO"
    NUM_0 .FILL	X-30
    NUM_9 .FILL X-39
.END