; PHEP TRU HAI SO KHONG DAU DUOC LUU TRONG O NHO CUA MAY TINH

.ORIG	x3000
    LDI R1, FIRST_NUM
    LDI R2, SECOND_NUM

    NOT	R2,	R2
    ADD	R2,	R2,	#1
    ADD	R1,	R1,	R2

    STI	R1,	RESULT

    HALT
    FIRST_NUM .FILL	    X4000
    SECOND_NUM .FILL	X4001
    RESULT  .FILL	X4002
.END