.ORIG X3000

IN           ; NHẬP GIÁ TRỊ ĐẦU VÀO
AND R1,R1,X0 ; KHỞI TẠO MẶT NẠ TRỐNG
ADD R1,R1,X1 ; MẶT NẠ BIT 1

LD	R2,	GIOI_HAN ; GIỚI HẠN TẦM THANH GHI MẶT NẠ SAO CHO KHÔNG LỐ TẦM MÃ ASCII

AND R3,R3,X0 ; KHỞI TẠO BIẾN ĐẾM

TIEP        AND R4,R0,R1 ;  CHO AND VỚI MẶT NẠ
            BRZ DETEC_ZER;  PHÁT HIỆN BIT 0 NÊN BỎ QUA VIỆC CỘNG BIẾN ĐẾM
            ADD R3,R3,1
DETEC_ZER   ADD R1,R1,R1  ; TẠO MASK MỚI CÓ ĐỘ DỜI BIT 1 SANG TRÁI 1 BIT
            ADD R4,R1,R2  ; XEM THỬ MASK CÓ ĐANG TRONG TẦM GIÁ TRỊ ASCII HAY KHÔNG
            BRN TIEP

LEA R0,TB       ; IN RA MÀN HÌNH THÔNG BÁO SỐ LƯỢNG BIT 1 CHƯƠNG TRÌNH ĐẾM ĐƯỢC
PUTS
AND R0,R0,X0

LD R1,ASCII     ; THỰC HIỆN CHUYỂN ĐỔI SỐ HEX SANG MÃ ASCII
ADD R0,R3,R1

OUT             ; IN RA MÀN HÌNH KẾT QUẢ
HALT
TB 	    .STRINGZ    "SL BIT 1 CO TRONG MA ASCII: "
ASCII       .FILL	X30
GIOI_HAN    .FILL	X-100
.END